name: SWarp
author: solo
version: 0.1.1
api:
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
- 3.0.0-ALPHA7
- 3.0.0-ALPHA8
- 3.0.0-ALPHA9
main: solo\swarp\SWarp
softDepend:
- EconomyAPI
permissions:
  swarp:
    default: op
    children:
      swarp.warp:
        default: op
        children:
          swarp.warp.default:
            default: true
          swarp.warp.op:
            default: op
      swarp.command:
        default: op
        children:
          swarp.command.warp:
            default: true
          swarp.command.create:
            default: op
          swarp.command.setdescription:
            default: op
          swarp.command.info:
            default: op
          swarp.command.list:
            default: true
          swarp.command.setoptions:
            default: op
          swarp.command.setpermission:
            default: op
          swarp.command.remove:
            default: op
          swarp.command.worldmove:
            default: op
